production:
    adapter: postgresql
    database: TagMeIfYouCan_production
    username: postgres
    password: password
    host: localhost
    encoding: UTF8

test:
    adapter: postgresql
    database: TagMeIfYouCan_test
    username: postgres
    password: password
    host: localhost
    encoding: UTF8
    
development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: TagMeIfYouCan_development
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
