development: &defaults
#  client_id: 242629845814737
#  client_secret: c409e1a66614ca0b5fd18a5748df5e74
  client_id: 252030558198465
  client_secret: b6024f4418eec1cb9d4accc50634a582
  scope: user_about_me,read_friendlists
  canvas_url: http://localhost:3000/
#  canvas_url: http://tagmeifyoucan.herokuapp.com/

test:
  <<: *defaults

production:
  <<: *defaults
